### ISSUE TITLE
standardize grid

### ISSUE THREAD

**Issue by MoralSiani** [ArielHorwitz/bot-royale#2]
Need to standardize grid, preferably (rows, columns) and (0,0) on top left.
ty

**Comment by ArielHorwitz** [comment]
So I was considering that we graduate to a hexagonal grid, just to make things more complicated :P

Actually hexagons are the bestagons. What do you think?

https://www.redblobgames.com/grids/hexagons/

**Comment by MoralSiani** [comment]
Agree
