### ISSUE TITLE
Action Validation for bots

### ISSUE THREAD

**Issue by imcrazeegamer** [ArielHorwitz/bot-royale#27]
The bots have no valid way of checking if a action will work and further more they don't have any way of knowing what the result of there action would be

I'm proposing we make a `check_valid_action(action: Action): -> bool` and a `simulate_action(action: Action): -> world_info`

this will allow us to **check and see outcomes of moves** also will allow us to **see if a move will win the game or not** 
(Would like the world_info to have a game_over_flag or something)

**Comment by ArielHorwitz** [comment]
+1

I suggest all pure game logic (check legal action, apply action, etc.) along with the `world_info` (world state) be moved to an independent module, which defines a state, actions, and can generate a new state given a state and an action.

This way also the bots and the "battle" class (Logic API) can use the these tools independently.

This will require some code migration and a small rework. It is being looked into.

**Comment by MoralSiani** [comment]
changes in progress

**Comment by ArielHorwitz** [comment]
Implemented in #36.
