### ISSUE TITLE
Choose python version

### ISSUE THREAD

**Issue by ArielHorwitz** [ArielHorwitz/bot-royale#54]
We should choose a version of python that is officially supported/required by the project. I suggest python 3.10. If we can get a consensus here that should be enough.

**Comment by imcrazeegamer** [comment]
well 3.10 is cool, always like new stuff, we just need to think about 3rd party pip repos that we probably want to use/ support and see if they can handle 3.10,
i know that tensorflow and pytorch for example can be problematic with specific python versions when tried to get it to work properly so its worth a look

**Comment by ArielHorwitz** [comment]
Just been reading [What's New in Python](https://docs.python.org/3/whatsnew/index.html) and did some testing on 3.8 and 3.9. At the moment 3.9 is the earliest that will run dev branch. I would be hesitant to accept a patch to dev to support 3.8 since I'm working on documenting the entire project and 3.8 lack support for some features of type annotation that I'm relying on.

I'm calling it at 3.9 and closing this issue. If there is concrete concern for this, the issue can be reopened.
