### ISSUE TITLE
New mechanics (actions or map features) 

### ISSUE THREAD

**Issue by ArielHorwitz** [ArielHorwitz/bot-royale#59]
As we stabilize the core of the codebase, we can begin to think of adding new in-game mechanics: new actions, or new map features (to add to walls, pits, and the ring of death).

This would be a change in `logic.state.State` and `api.actions`.

**Comment by imcrazeegamer** [comment]
if anyone has ideas speak up im currently working on tiles that trigger what im calling a State Reaction (a method that is called when stepped on N times)
that will open the door for so many new mechanics.
currently im prototyping a tile that turns in to a pit after stepping on it N times and a tile that decreases death radius after after stepping on it N times

**Comment by FriedlandAaron** [comment]
This shit sounds awesome! If you guys have played fall guys, one thing i can think of is the falling tiles, so basically tiles that become impossible to move to after stepping on them

**Comment by imcrazeegamer** [comment]
@FriedlandAaron ya that would be possible would require some work though

**Comment by FriedlandAaron** [comment]
Trap tiles! After stepping on a trap tile, the tile gets surrounded by pits, forcing the bot to jump in order to escape.
And maybe a new action can be added to try and counter traps, like a scan action that can look for traps in a close radius.

**Comment by imcrazeegamer** [comment]
Plate is on dev, there are 3 types go play with it and let me know what you think

**Comment by ArielHorwitz** [comment]
> Plate is on dev, there are 3 types go play with it and let me know what you think

I would consider this a sizeable feature for maps, and good for what we need for now. Plates could also let us add many arbitrary effects should we wish.
