### ISSUE TITLE
Bots need to get information about the game state

### ISSUE THREAD

**Issue by ArielHorwitz** [ArielHorwitz/bot-royale#6]
When a bot is called to action, it should receive some sort of game state data. Currently there are only random bots that don't require any knowledge of the game state.

_It is probably preferable that the bots receive some copy and not direct access to the game data (numpy arrays in particular)._

### BaseBotAPI
Thinking about it, perhaps the Logic maintainer @MoralSiani can make a `BaseBotAPI` class similar to `BaseLogicAPI`. That way they can more easily add new features available to the bots without requiring simultaneous updates in both `logic` and `bots` packages?

**Comment by imcrazeegamer** [comment]
i need moral

**Comment by imcrazeegamer** [comment]
@MoralSiani everything is in dev just need you to implement it

**Comment by MoralSiani** [comment]
Done
